### ISSUE TITLE
Triggers on concave MeshColliders are not supported

### ISSUE THREAD

**Issue by 7ranceaddic7** [dunclaw/HLAirships#5]
[LOG 21:45:08.038] PartLoader: Part 'HLAirships/Parts/Aero/HL_AirshipEnvelope_Hecto/part/HL_AirshipEnvelopeHecto' has no database record. Creating.
[ERR 21:45:08.039] Triggers on concave MeshColliders are not supported

[LOG 21:45:08.135] PartLoader: Part 'HLAirships/Parts/Aero/HL_AirshipEnvelope_LudoBlimp/part/Blimp' has no database record. Creating.
[ERR 21:45:08.137] Triggers on concave MeshColliders are not supported

[LOG 21:45:08.230] PartLoader: Part 'HLAirships/Parts/Aero/HL_AirshipEnvelope_Octo/part/HL_AirshipEnvelope_Octo' has no database record. Creating.
[ERR 21:45:08.232] Triggers on concave MeshColliders are not supported

**Comment by StoneBlue** [comment]
Unfortunately, a past KSP/Unity update stopped supporting the use of concave colliders, AT ALL, in the game.
This is just warning spam in the logs, as IIRC, the parts *should* still function properly? vOv

In any case, to fix it, would require redoing the colliders in the models, which would also require redoing the animations, I believe... possibbly other stuff I cant think of...
So, basically, quite a bit of modelling work...

**Comment by JewelShisen** [comment]
Octo, Hecto, and Blimp are all static parts with no animations so it would only need an update in Unity. This will be addressed in the next update of the mod.
