### ISSUE TITLE
Cannot clone model as model does not exist

### ISSUE THREAD

**Issue by 7ranceaddic7** [dunclaw/HLAirships#6]
[LOG 21:45:09.548] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepBay10mtr/ZepBay10mtr'
[ERR 21:45:09.551] PartCompiler: Cannot clone model 'HLAirships/Parts/Aero/ZepKit/ZepBay10mtr' as model does not exist

[ERR 21:45:09.551] PartCompiler: Model was not compiled correctly

[ERR 21:45:09.551] PartCompiler: Cannot compile model

[ERR 21:45:09.551] PartCompiler: Cannot compile part

[LOG 21:45:09.551] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepMidHull/ZepMidHull'
[ERR 21:45:09.553] PartCompiler: Cannot clone model 'HLAirships/Parts/Aero/ZepKit/ZepMidhull' as model does not exist

[ERR 21:45:09.553] PartCompiler: Model was not compiled correctly

[ERR 21:45:09.553] PartCompiler: Cannot compile model

[ERR 21:45:09.553] PartCompiler: Cannot compile part

[LOG 21:45:09.553] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepMidHull2mtr/ZepMidHull2mtr'
[LOG 21:45:09.588] PartLoader: Part 'HLAirships/Parts/Aero/ZepKit/ZepMidHull2mtr/ZepMidHull2mtr' has no database record. Creating.
[LOG 21:45:09.597] DragCubeSystem: Creating drag cubes for part 'ZepMidHull2mtr'
[LOG 21:45:09.606] [Telemachus Debug] Flight globals was null during start up; skipping update of vessel change.
[LOG 21:45:09.637] [Telemachus Debug] Flight globals was null during start up; skipping update of vessel change.
[LOG 21:45:09.644] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepMidNose/ZepMidNose'
[ERR 21:45:09.647] PartCompiler: Cannot clone model 'HLAirships/Parts/Aero/ZepKit/ZepMidNose' as model does not exist

[ERR 21:45:09.647] PartCompiler: Model was not compiled correctly

[ERR 21:45:09.647] PartCompiler: Cannot compile model

[ERR 21:45:09.647] PartCompiler: Cannot compile part

[LOG 21:45:09.647] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepMidTailCone/ZepMidTailCone'
[ERR 21:45:09.650] PartCompiler: Cannot clone model 'HLAirships/Parts/Aero/ZepKit/ZepMidTailCone' as model does not exist

[ERR 21:45:09.650] PartCompiler: Model was not compiled correctly

[ERR 21:45:09.650] PartCompiler: Cannot compile model

[ERR 21:45:09.650] PartCompiler: Cannot compile part

[LOG 21:45:09.650] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepNoseCone/ZepNoseCone'
[ERR 21:45:09.652] PartCompiler: Cannot clone model 'HLAirships/Parts/Aero/ZepKit/Zepnosecone' as model does not exist

[ERR 21:45:09.652] PartCompiler: Model was not compiled correctly

[ERR 21:45:09.652] PartCompiler: Cannot compile model

[ERR 21:45:09.652] PartCompiler: Cannot compile part

[LOG 21:45:09.652] PartLoader: Compiling Part 'HLAirships/Parts/Aero/ZepKit/ZepTailCone/ZepTailCone'
[ERR 21:45:09.654] PartCompiler: Cannot clone model 'HLAirships/Parts/Aero/ZepKit/ZepTailcone' as model does not exist

[ERR 21:45:09.654] PartCompiler: Model was not compiled correctly

[ERR 21:45:09.654] PartCompiler: Cannot compile model

[ERR 21:45:09.654] PartCompiler: Cannot compile part

**Comment by StoneBlue** [comment]
Another Issue I included in, but should have read before I posted Issue #10.

The models just do not exist, as declared in model definitions, in the part cfgs.
Either the cfgs should be removed from the release package, or disabled from loading, by changing the file extension to `.txt` or something, to keep them from trying to load.

@JewelShisen you can probably close this issue now, as I basically combined/duplicated it in Issue #10

**Comment by JewelShisen** [comment]
ZepKit parts will be dropped in the next update as I do not have the source models to repair the broken parts.
